# This file creates two columns for the distinct types and subtypes currently coded in the dataset
# note that for the original excel file submitted to Chris, release_long was only ran until the '# add in update information' line in 2_release_data.R
release_long = read_csv("data/CoronaNet/coronanet_release.csv")

type_who = release_long %>% select(type, type_sub_cat) %>% distinct

type_who$type_sub_cat = forcats:::fct_relevel(type_who$type_sub_cat , c("Self-Quarantine (i.e. quarantine at home)",
                                                                           "Government Quarantine (i.e. quarantine at a government hotel or facility)",
                                                                           "Quarantine outside the home or government facility (i.e. quarantine in a hotel)",
                                                                           "Quarantine only applies to people of certain ages. Please note the age restrictions in the text box.",
                                                                           "Other Quarantine",
                                                                           "Health Screenings (e.g. temperature checks)" ,
                                                                           "Health Certificates",
                                                                           "Travel History Form (e.g. documents where traveler has recently been)",
                                                                           "Visa restrictions (e.g. suspend issuance of visa)",
                                                                           "Visa extensions (e.g. visa validity extended)",
                                                                           "Other External Border Restriction",
                                                                           "Cancellation of an annually recurring event" ,
                                                                           "Postponement of an annually recurring event",
                                                                           "Cancellation of a recreational or commercial event",
                                                                           "Postponement of a recreational or commercial event",
                                                                           "Attendance at religious services prohibited (e.g. mosque/church closings)",
                                                                           "Prison population reduced (e.g. early release of prisoners)",
                                                                           "All public spaces / everywhere",
                                                                           "Inside public or commercial building (e.g. supermarkets)",
                                                                           'Unspecified Mask Wearing Policy',
                                                                           'Other Mask Wearing Policy',
                                                                           "Wearing masks",
                                                                           "Preschool or childcare facilities (generally for children ages 5 and below)" ,
                                                                           "Primary Schools (generally for children ages 10 and below)"  ,
                                                                           "Secondary Schools (generally for children ages 10 to 18)"  ,
                                                                           "Higher education (i.e. degree granting institutions)" ,
                                                                           "Restricted issuing of permits/certificates and/or processing of government documents"  ,
                                                                           "Beaches"  ,
                                                                           "Campsites",
                                                                           "Parks",
                                                                           "Tourist Sites",
                                                                           "Unspecified outdoor spaces",
                                                                           "Other public outdoor spaces",
                                                                           'Public libraries',
                                                                           'Public museums/galleries',
                                                                           'Unspecified public facilities',
                                                                           'Other public facilities',
                                                                           'Restricted government working hours (e.g. work from home policies for government workers)',
                                                                           'All non-essential government services restricted',
                                                                           "Retail Businesses",
                                                                           "Restaurants/Bars" ,
                                                                           "Shopping Centers" ,
                                                                           "Non-Essential Commercial Businesses" ,
                                                                           "Personal Grooming Businesses (e.g. hair salons)",
                                                                           "Other Businesses",
                                                                           "All or unspecified non-essential businesses",
                                                                           "Masks",
                                                                           "Ventilators",
                                                                           "Personal Protective Equipment",
                                                                           "Hand Sanitizer" ,
                                                                           "Test Kits" ,
                                                                           "Vaccines",
                                                                           "Unspecified Health Materials",
                                                                           "Other Health Materials",
                                                                           "Hospitals",
                                                                           "Temporary Quarantine Centers",
                                                                           "Temporary Medical Centers",
                                                                           "Public Testing Facilities (e.g. drive-in testing for COVID-19)" ,
                                                                           "Health Research Facilities",
                                                                           "Unspecified Health Infrastructure",
                                                                           "Other Health Infrastructure",
                                                                           "Doctors" ,
                                                                           "Nurses" ,
                                                                           "Health Volunteers" ,
                                                                           "Unspecified Health Staff" ,
                                                                           "Other Heath Staff",
                                                                           "Health Insurance",
                                                                           "Hygiene measures for commercial areas"  ,
                                                                           "Hygiene measures for public areas"   ,
                                                                           "Hygiene measures for public transport"  ,
                                                                           "Burial procedures",
                                                                           "Other Areas Hygiene Measures Applied",
                                                                           "Disseminating information related to COVID-19 to the public that is reliable and factually accurate"  ,
                                                                           "Gathering information related to COVID-19 from the public"  ,
                                                                           "Both Disseminating and Gathering information related to COVID-19",
                                                                           "New Task Force or Bureau (i.e. establishment of a temporary body)"  ,
                                                                           "Existing government entity given new powers"  ,
                                                                           "Cooperation among different jurisdictional entities (e.g. treaties or agreements among countries or provinces)",
                                                                           "Other Administrative Configurations"
))

type_who$type = forcats:::fct_relevel(type_who$type, c(
  "Declaration of Emergency",
  "Quarantine/Lockdown",
  "External Border Restrictions",
  "Internal Border Restrictions",
  "Restrictions of Mass Gatherings",
  "Social Distancing",
  "Curfew" ,
  "Closure of Schools",
  "Restriction of Non-Essential Government Services" ,
  "Restriction of Non-Essential Businesses",
  "Health Monitoring",
  "Health Testing", 
  
  "Health Resources" ,
  "Hygiene",
  "Public Awareness Measures",
  "Anti-Disinformation Measures",
  "New Task Force, Bureau or Administrative Configuration",
  "Other Policy Not Listed Above"))
type_who  = type_who %>%
  arrange(type, !is.na(type_sub_cat), type_sub_cat)
names(type_who) = c('Category', 'Sub-Category')


write.csv(type_who, file = "data/CoronaNet/categories_who.csv", row.names = F)
